// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwg7MIKEuSzysp51h7a1CzTZcHWZSozCU',
    appId: '1:563912762714:web:21169f18985521f83c3f63',
    messagingSenderId: '563912762714',
    projectId: 'fungo-app-c9239',
    authDomain: 'fungo-app-c9239.firebaseapp.com',
    storageBucket: 'fungo-app-c9239.firebasestorage.app',
    measurementId: 'G-JJF97QHR4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH2XId9_qUX12j-le4BKEaceQe39v907Q',
    appId: '1:563912762714:android:057d81106f4e16433c3f63',
    messagingSenderId: '563912762714',
    projectId: 'fungo-app-c9239',
    storageBucket: 'fungo-app-c9239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL3zehfOptRG7oblRwWeupecNL7jQ3AaI',
    appId: '1:563912762714:ios:f6c1f279b8ca8c3b3c3f63',
    messagingSenderId: '563912762714',
    projectId: 'fungo-app-c9239',
    storageBucket: 'fungo-app-c9239.firebasestorage.app',
    iosBundleId: 'com.example.funGoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL3zehfOptRG7oblRwWeupecNL7jQ3AaI',
    appId: '1:563912762714:ios:f6c1f279b8ca8c3b3c3f63',
    messagingSenderId: '563912762714',
    projectId: 'fungo-app-c9239',
    storageBucket: 'fungo-app-c9239.firebasestorage.app',
    iosBundleId: 'com.example.funGoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwg7MIKEuSzysp51h7a1CzTZcHWZSozCU',
    appId: '1:563912762714:web:8fa0cd7e1a2351c03c3f63',
    messagingSenderId: '563912762714',
    projectId: 'fungo-app-c9239',
    authDomain: 'fungo-app-c9239.firebaseapp.com',
    storageBucket: 'fungo-app-c9239.firebasestorage.app',
    measurementId: 'G-E670HVQK24',
  );
}
